---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    image: fedora:38
    pre_build_image: true
lint: |
  set -e
  yamllint . -c .yamllint
  ansible-lint -c .ansible-lint
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../roles/
verifier:
  name: ansible
scenario:
  name: default
  test_sequence:
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - destroy
