---
# Tweaks

## Apperance
icon_theme: ePapirus-Dark
user_theme_name: Catppuccin-Frappe-Standard-Rosewater-Dark
gtk_theme: Catppuccin-Frappe-Standard-Rosewater-Dark

## Font
monospace_font_name: Source Code Pro Medium 12
font_name: Cantarell 11
document_font_name: Cantarell 11

## Windows title bar
action_double_click_titlebar: toggle-maximize
action_middle_click_titlebar: minimize
action_right_click_titlebar: toggle-maximize