---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - fedora38
    steps:
      - name: Checkout code base
        uses: actions/checkout@v3
        
      - name: Set up python 3
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install test dependency
        run: pip3 install molecule-plugins[lint,podman] 
      
      - name: Run molecule test
        run: molecule test
